### ISSUE TITLE
Editors always are 'anonymous' in Onlyoffice

### ISSUE THREAD

**Issue by zirkeltraining** [ONLYOFFICE/onlyoffice-owncloud#13]
it's great that collaborative editing works, but it's a problem that OO doesn't know the name of the editing user. The commenting feature and the track changes feature list all concurrent users equally as "Anonymous" with a random color. 

Do you have any plans to work on that? Because this flaw IMHO makes the OC-OO connector less functional in comparison to just linking the OC into the OO file manager.

**Comment by JohnPerkin** [comment]
Showing users for collaborative editing in ONLYOFFICE was developed since the first version and we hasn't face any issues till the current moment. In the attached screenshot the same document is opened by one user in two tabs. Another user was granted access for editing this document. Different users are highlighted by different colours.
![issue13](https://cloud.githubusercontent.com/assets/25245782/23553897/d55619b2-0033-11e7-9932-0a8baf487725.png)
You may give us additional information concerning the problem: in the source code of the page when opening the editor there is a javascript calling method OCA.Onlyoffice.OpenEditor at the bottom of the page. What meaning is set for the parameter 'userId'?

**Comment by zirkeltraining** [comment]
Hey, that's quick. Thanks! 
![screen shot 2017-03-03 at 3 14 18 pm](https://cloud.githubusercontent.com/assets/26162293/23554140/1d3f7814-0024-11e7-85ec-5ded9d11af6c.png)
The screenshot shows me logged in on 2 different browsers with different user names. But both are only shown as "Anonymous".
however in OCA_Onlyoffice.OpenEditor the correct OC User name is listed:
for example browser 1:
`            userId: "dummyuser-di",

            userName: "dummyuser-di",`

**Comment by JohnPerkin** [comment]
Please specify the virsion of Document Server. 
Try to open one document in two tabs by one user. In the list of users the person should appear twice with the same colours as on the screen in our previous message. Do you have the same scenario or user is highlighted by different colours?

**Comment by zirkeltraining** [comment]
our oo is Version 8.9.2.19

When i open the same document in two tabs as the same user, i see two users in the same color, both are called "Anonymous".

**Comment by JohnPerkin** [comment]
8.9.2.19 is the version of Community Server. Please tell us version of Document Server.

**Comment by zirkeltraining** [comment]
sorry. Where do i find that? (our friendly admin is out of the office)
Document Editor says 4.1. 
OnlyOffice/OC App is 1.0.0

**Comment by JohnPerkin** [comment]
Please update your Document Server to the version 4.2 as it has some changes in the source code in comparison to 4.1
Specify method of installation and we could give you instruction how to perform update.

**Comment by zirkeltraining** [comment]
Yes, that fixed it! Thank you very much. Solved!

**Comment by LinneyS** [comment]
checking version of onlyoffice https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/013282e8c8af8c15a19c80abb484969d33a82064
