### ISSUE TITLE
HAProxy Nextcloud Plugin Error (HTTPS <-> HTTP)

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/onlyoffice-owncloud#136]
1. Create or open a new Document
2. Empy Site opens (only the Topbar from NC is there)

![haproxy](https://user-images.githubusercontent.com/33482537/33836482-d0dbdcd4-de89-11e7-9947-63b5daec3463.png)

Error: "Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf http://xxxy.com/2017-11-24-15-41/web-apps/apps/presentationeditor/main/index.html?_dc=2017-11-24-15-41&lang=de-DE&customer=ONLYOFFICE&frameEditorId=iframeEditor blockiert ("frame-src https://xxxy.com/")."

I dont have access to HAProxy, but could it be the problem, theres no rewrite to HTTPS.
Settings accepted in Nextcloud. OO reachable trough direct URL

**Comment by agolybev** [comment]
Hi @ExaconAT,  I think it's a proxying issue. See [here](https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx) how to set up proxing for Document Server.

**Comment by ExaconAT** [comment]
Found the Solution: Add to Backend: reqadd X-Forwarded-Proto:\ https or in frontend Https

**Comment by danielsteiner** [comment]
I am really sorry for highjacking this issue but I can't find any source of information on how to realise a proxied scenario with Traefik **2** - the official onlyoffice documentation only gives info on traefik 1.x.  
I am currently getting an CORS error (to be precise: wss is not in the list of allowed protocols) and I am very sure, that this is because I don't have the `X-Forwarded-Proto` and/or `X-Forwarded-Host ` header set respectively can't set them in a way that is described in the docs. 

Has anyone got an idea how to fix this?

**Comment by jjasoncool** [comment]
> Found the Solution: Add to Backend: reqadd X-Forwarded-Proto:\ https or in frontend Https

Thank you!
this help me out!

**Comment by ant0nwax** [comment]
Hi @ExaconAT 

I found your thread because the OnlyOffice Update does not work for my Nextcloud integration since version 7.0, still with version 7.3.2 i cannot update the document server, because we cannot edit documents anymore.

the thread where I documented a lot about my issues is located here:
https://github.com/ONLYOFFICE/DocumentServer/issues/2083#issuecomment-1431126485

so basically I have an issue in understanding how me as httpd admin could use the sentence:
"Add to Backend: reqadd X-Forwarded-Proto:\ https or in frontend Https"
 It might be an information for developers but could also be information for integrators, could you please edit this information to make it clear with an example? Thank you.
