### ISSUE TITLE
Lost files ...

### ISSUE THREAD

**Issue by ManuelRighi** [ONLYOFFICE/onlyoffice-owncloud#140]
Hello,
I have OnlyOffice Document Server version 4.4.3-7 installed on Ubuntu Server 16.04 LTS.
This is integrated with my owncloud version 10.0.2 with app OnlyOffice versione 1.1.6.
Today my all xlsx documents are empty.
I see thath onlyoffice document server never update my physical files in the owncloud, but I think save xlsx files only on the document server.

I need to restore files ...

Can you help me ?
Thanks
Manuel

**Comment by alexanderonlyoffice** [comment]
Hello @ManuelRighi,

Could you please send us an email to support@onlyoffice.com

Please send us a screenshot of ONLYOFFICE address settings in OwnCloud administrator section. Specify also if there were any errors when you had saved address settings after having entered the address of the document server. We look forward to your reply in our support system.

**Comment by ManuelRighi** [comment]
Thanks Alesander, I send email now.

Manuel

**Comment by alexanderonlyoffice** [comment]
Hello @ManuelRighi,

As we have answered you in our support system helpdesk.onlyoffice.com, unfortunately, there is no possibility to restore those files.

The reason of the problem, as we can see in the logs, that there was no connection with the document server, because address settings were not saved and applied from the very beginning.
