### ISSUE TITLE
Menu inconsistency (in NextCloud directory listing)

### ISSUE THREAD

**Issue by DavidPatShuiFong** [ONLYOFFICE/onlyoffice-owncloud#17]
When clicking on the '3-dot' menu to the right of an '.odt' Libre/OpenOffice document shown in NextCloud 11 directory listing, the resulting drop-down menu includes 'Open in OnlyOffice' (as well as 'Details', 'Rename', "Delete' etc.). OnlyOffice only offers to convert the file into something like .docx which is fine, but...

when clicking the same '3-dot' menu to the right of a '.docx' document, there is no 'Open in OnlyOffice' option! Clicking on the filename itself opens the document in OnlyOffice, which is great, but inconsistent.

**Comment by JohnPerkin** [comment]
Hello!
This is a feature of ONLYOFFICE which was implemented upon users' request https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/4#issue-205389363. 
Document Server opens .docx, .xlsx and .pptx by clicking on those files. Other files can be opened from drop-down menu.

**Comment by nommaz** [comment]
we dont use odt, sorry if i provided incomplete requirements. Wouldnt have any objection to any other type being handled by onlyoffice on title click with the exception of image, text and markdown.

**Comment by DavidPatShuiFong** [comment]
Thanks for your replies!
My apologies, my issue description didn't really make clear which inconsistency I was referring to!

Although I use .odt files, I am not extremely concerned that OnlyOffice does not edit .odt files (because, sadly, I realize that most of the world doesn't use .odt)
But if conversion is all that OnlyOffice is offering, that is what should be stated in the 'drop-down' menu 'Convert with OnlyOffice' instead of 'Open in ONLYOFFICE'

By contrast, I expected the option 'Open in ONLYOFFICE' to be available for .docx files, although I know .docx can also be opened for editing just by clicking on the filename.

**Comment by Stibila** [comment]
This inconsistency is a feature? I just spent 1 hour of trying to figure out, why I can't open .docx .xlsx etc in ONLYOFFICE. I didn't try to click on the file itself, because I already know, this action will result in downloading the file and that's not what I wanted. I didn't realize that you would hijack 'click on the file' function and go against everything user know. This is excellent example of  bad design, of ignoring UX.

Although clicking on the file is not as bad, as removing 'Open in ONLYOFFICE' from 3-dot menu.
Why would you put same function to 2 different places based on file extension? Whose idea was that? Now user have to learn and remember where to click to open files with which extensions.

Correct way is to either open all files by clicking on them, or put 'Open in ONLYOFFICE' inside 3-dot menu for all files. Or both. But be consistent.

**Comment by JohnPerkin** [comment]
Hello!
We added to context (3-dot) menu the operation 'onlyofficeOpen'.
For the ability to perform exactly this action by clicking on the file name we specified it as a default operation.
https://github.com/ONLYOFFICE/onlyoffice-owncloud/blob/master/js/main.js#L148
But owncloud hides the default action from context menu for some reasons.
https://github.com/owncloud/core/blob/master/apps/files/js/fileactionsmenu.js#L110
We are ready to improve the situation if we will be given a hint how to perform it.

**Comment by Stibila** [comment]
"But owncloud hides the default action from context menu for some reasons." - I didn't know that. In that case that's bad design on their end.
One solution would be to not specify default operation, or specify it on every file ONLYOFFICE can open. Better yet give users option to select preferred behavior in admin settings.

**Comment by JohnPerkin** [comment]
We will take your suggestion into consideration. Thank you for the interest in ONLYOFFICE.
