### ISSUE TITLE
[FEATURE REQUEST] Add odt/ods extensions to open automatically

### ISSUE THREAD

**Issue by hostingnuggets** [ONLYOFFICE/onlyoffice-owncloud#179]
Currently only docx/xlsx/etc. file extensions open automatically in OnlyOffice. Would it be possible to add the odt/ods/etc (LibreOffice/OpenOffice) extensions to the list of extensions which can be automatically opened by OnlyOffice?

Thanks!

**Comment by ferfebles** [comment]
We are evaluating Nextcloud-OnlyOffice in a University environment, but the workflow for LibreOffice documents (duplicate as a Microsoft converted file, edit and convert again to LibreOffice) is something that we cannot explain to our users, as we massively use LibreOffice formats in our documents.

Is it possible to autoconvert the files on opening and saving without the need for manual conversion?

**Comment by alexanderonlyoffice** [comment]
Hello @ferfebles, unfortunately, we are not planning to include these formats into the list of supported output formats for the NC/OC connector.

**Comment by quenenni** [comment]
Then it's unfortunately a no go for us.

That's a bit sad as I just finished my install and were quite impress by the first look at onlyoffice.. until I discover this detail.

Well, Lool it will be.
Good luck with your project.

**Comment by tavinus** [comment]
Hi! @quenenni, @LinneyS 's [commit](https://github.com/ONLYOFFICE/onlyoffice-owncloud/commit/233f0df9cd1b65286059929fe921db4a1bf4010e) actually adds everything as an option to be opened by OnlyOffice. You can change on the config.  
  
--------------------------------------------------------------

### On Config > OnlyOffice
![image](https://user-images.githubusercontent.com/8039413/45342276-cf626a00-b573-11e8-961b-5ee973f2c9d8.png)
  
--------------------------------------------------------------
  
### Now we also have two actions available for files (Open AND Convert)  
![image](https://user-images.githubusercontent.com/8039413/45342348-105a7e80-b574-11e8-9299-c30683e47061.png)
  
--------------------------------------------------------------
  
**However, whenever I open a file that is not `docx, pptx, xlsx` my main menu with the tools is gone from the top.** The menu shows fine for the default file types though. Here an odt example:   
  
![image](https://user-images.githubusercontent.com/8039413/45342676-0ab16880-b575-11e8-83ac-58fe2a0a2fb5.png)
  
So, even though the files open, we can't really edit them without the top menu.  
Any ideas on how to fix the menu?   
As mentioned, only the three default formats have the menu working.

**Comment by tavinus** [comment]
Ok, nevermind... I realised it says `"Document Viewer"` there now.  
So, we can set it as default, but that is read-only.  
That was not so clear from the config and the interface is very similar so I got confused, sry...

**Comment by LinneyS** [comment]
[Please note](https://api.onlyoffice.com/editors/owncloud#editable)

**Comment by tavinus** [comment]
Thanks for the link!  
  
I have updated my OnlyOffice app in Nextcloud and now I can enable editing for more stuff (with the important note that double-conversion may cause loss of data). Conversion is always available anyways, so this seems like a great solution overall. **Good job!**  
  
However, now I need to translate that new line of text on the config to Brazilian Portuguese.
![image](https://user-images.githubusercontent.com/8039413/45399378-2a509b80-b61e-11e8-8183-16e7c8227229.png)
  
Can you just add it to the Brazilian portuguese files?  
It is kind of hard for me to clone, rebase, change at the moment. And also I currently don't have a test setup to try it as well (will have to try on production).  

### String missing
`"Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)"`
  
translates to  
  
`"Habilitar edição (devido à restrição dos formatos, dados podem ser perdidos ao salvar nos formatos abaixo)"`  
  
If it is hard for you I will probably do a PR in a few days.  
Cheers!  
Gus

**Comment by alexandervnuchkov** [comment]
Thank you very much @tavinus for the translation, we will apply it in the develop branch and it will be available for all in the next release.
