### ISSUE TITLE
Shared document to open in ONLYOFFICE

### ISSUE THREAD

**Issue by mmarif4u** [ONLYOFFICE/onlyoffice-owncloud#20]
Hi,
I am using ONLYOFFICE in NextCloud and everything works so far. Thanks for the great product.
Only issue i came across is when i share a shared link for document where the user is not part of the NC system. It shows download link for the document.

Expected behavior: open the shared link with others(not NC users) in read only mode in ONLYOFFICE instead of download action.

Is it there and i am missing something?

**Comment by JohnPerkin** [comment]
Hello!
This option is not included in ONLYOFFICE. Thank you for the suggestion, we will take it into consideration.
Best regards
John
ONLYOFFICE support team

**Comment by mmarif4u** [comment]
Thanks John for considering this feature.
Hope not asking for more, it will be fantastic if it have the edit checkbox similar to NC local users in case some one want to share a protected document with colleagues and want them to work together on it.
Its just a suggestion.

**Comment by zirkeltraining** [comment]
+1 for this feature request. The strength of OO is that you don't need to install anything, so being able to share editable files via OC would be a major advantage.

**Comment by penzoiders** [comment]
+1 for this feature request. will basically remove the need of using google spreadsheets if you have OC/NC + OO document server

**Comment by Schmuuu** [comment]
+1 I hope this features comes soon, because I need it very much.

**Comment by jones4410** [comment]
+1 Great software! - Really the only thing I'm missing!

**Comment by Dave-REBL** [comment]
+1 Also looking forward to this feature. We have many docx and xlsx files in Nextcloud that are in read-only folders ("You don't have permission to upload or create files here") and there is no option to view the files, only download. This feature would make OnlyOffice integration with Nextcloud so much better.

**Comment by jkaberg** [comment]
I'd to would liek to see possibilities for guests **viewing and editing** through Nextcloud

**Comment by pulcov** [comment]
+1 for this feature

**Comment by e-tagirov** [comment]
+1

**Comment by NEWGithuber1991** [comment]
Me Too !

**Comment by maprambo** [comment]
+1

**Comment by js94x** [comment]
+1

**Comment by mmarif4u** [comment]
Any update on this @JohnPerkin @LinneyS

**Comment by e-alfred** [comment]
This would be a good feature to have especially now that Nextcloud 12 allows publicly editable files with Collabora CODE.

**Comment by styx-tdo** [comment]
+1

**Comment by pulcov** [comment]
Is there any plan to integrate this feature ?
Thx for your reply.

**Comment by bctpro** [comment]
https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/50
says this works, but it does not in our scenario.

Sharing a folder to the public (a user without a nextcloud profile) does not run openoffice, it only allows the user to download the document.

Nextcloud v12.03
OpenOffice CE v17.08.125

**Comment by alexanderonlyoffice** [comment]
@bctpro, please note that we do not offer support for OpenOffice software.

**Comment by compumatter** [comment]
+1 for this feature.  Using OnlyOffice in NextCloud.  Huge plus is for shared documents to have live editing.  This is a major handicap

**Comment by ErmoM** [comment]
is this feature included now ?

**Comment by bctpro** [comment]
@alexanderonlyoffice 
A public user (a user without an account), goes to a NectCloud v12.03 share folder.
The public user tries to view a document in the share folder but onlyoffice does not open, instead the document

**Comment by bctpro** [comment]
...downloads.   A registered user is able to open the same document and onlyoffice will start.

**Comment by styx-tdo** [comment]
@alexanderonlyoffice this request is regarding the plugin. 
If the user is registered, OO webinterface opens.
If the visitor has edit rights via a shared link, the file downloads.
We'd like: If an user has edit rights (no matter if it is as owncloud user or visitor), OO should open.

Maybe the issue is that you rely on  $this->userSession->getUser()->getUID() which may not work for visitors with edit rights

**Comment by BetaLeaf** [comment]
Looking for support on this as well. Please implement this. It's been 10 months since the issue opened.

**Comment by steampoweredlawngnome** [comment]
It would appear development has stalled. What little activity there has been on the plugin and the product as a whole suggests there is very little developer interest. I will migrate to Collabora CODE. It isn't as nice aesthetically yet, but at least it's being actively developed.

**Comment by BetaLeaf** [comment]
I just tested collabora and I immediately switched back to onlyoffice. I couldn't freeze the top row so when I scroll down it remained on screen at all times. That and the interface was really ugly. Just my 2 cents.

**Comment by mmarif4u** [comment]
Almost going to be a year now and i believe there is no still news on this. @JohnPerkin @LinneyS

**Comment by Schmuuu** [comment]
This must actually be the most requested feature, or at least it is the most needed feature by me. Collabora Online would be left way behind as a competitor with this feature. Too bad it isn't released yet.

**Comment by BetaLeaf** [comment]
I agree. As an alternative, I have set password security within Nextcloud to 5 characters and have an account guest:guest with 0 quota that has access to the file. With this, they just need to know the account info guest:guest and I can set rather they get view/edit permission on a per file basis. the 0 quota prevents them using up storage (they can still abuse this and create an infinite amount of folders, which could obscure the files I shared with the guest account)

**Comment by onny** [comment]
I was able to "hack" public editing of documents into the source code by disabling user authentication to the editor page and by hardcode some file informations into the ajax response.
![Uploading 2018-02-10-213819_swaygrab.png…]()
I'll try to continue this work even though the code won't be in good enough for a pull request ...

**Comment by ibnpetr** [comment]
@onny Ok, you changed the sources to disable the authentication.
Now you have a warning in the web interface that "There were problems with the code integrity check."
All changed files are now listed as "invalid" in the Nextcloud/Owncloud
Hope you understand that the plugin with disabled authentication won't be approved in any marketplace.

**Comment by plimo** [comment]
@ibnpetr I think @onny is well aware of this fact, as he stated it by himself: "the code won't be good enough for a pull request". 

But as people like to use onlyoffice but the lack of possibility to edit public shared documents is a major disadvantage, they try to find solutions by themselves - at least as long as no developer ever gives any hints if this requested functionality will ever be supported...

**Comment by Mikescops** [comment]
@ibnpetr Why are you so rude with that guy? This feature should be on your top list at the time, it's a really important improvement for collaboration.

**Comment by Schmuuu** [comment]
I really appreciate that at least one person is working on it and trying his best to provide this feature. 
It is nearly a year, since this feature was requested by this issue and we haven't had any feedback from the developers if they work on this feature or if they will work on it at any time.
I mean, information is key - especially to calm down the mob ;)

Maybe this feature's importance is totally underrated by the developer team. Let me give some examples, why I or better say we (my users, friends and colleagues) need it:

1. A friend created an excel sheet for sport activities with Google Docs and shared it with around 15 people publicly. Every user can just access this excel sheet and enter his personal sport activities, what exercise he did, how many reps and so on. It creates a very nice competition and everyone is highly motivated to do his sports (because others can see if there are no more entries).

2. For my sports club I created an excel sheet with Google Docs where everybody (about 60 users) can write down if he comes to the next course and so on. (I know it sounds like you could achieve that with a calendar, but it has its reasons. Short: much better overview).

3. I don't know what kind of data and documents, but users want to publicly share and co-edit documents with external people.


My users ask me regularly when this feature will finally come. About 3 weeks ago a user said: "When this feature doesn't come soon, we definitely need to switch to Collabora." 
We all agree, that Onlyoffice is the nicer and better solution in regards to the editor itself and the MS Office compatibility. But this feature here is missing too much. 

Actually by setting up my personal Nextcloud and installing Onlyoffice I wanted to de-google my life and right now I'm very sad I can't fully do that.

Furthermore I planned to advertise Nextcloud in combination with Onlyoffice to my company. But to fully convince everybody, that Onlyoffice is a great alternative to Google Docs, I also waited for this feature. 
Sounds strange, but for me really a lot depends on this feature.

**Comment by ibnpetr** [comment]
> This feature should be on your top list at the time

@Mikescops We understand that this is one of the most important features, it's a matter of time...

@onny I'm really **sorry** if that seemed rude, it is just a comment about possible security issues. Disabling authentication is not the way to go if we want to add the external share. It is very important for our team to keep the integration secure.

**Comment by e-alfred** [comment]
@ibnpetr Not being able to share with outsiders who don't have an account is basically what prevents users from using Onlyoffice and going forward with Collabora or even Google Docs/Microsoft Online Office/whatever. You should reconsider your priorities.

**Comment by penzoiders** [comment]
Since I'd love this feature too, as many out there (and it's the only thing that is missing to totally dump gdocs in several companies), I'd love if we can sort this out.

I have a suggestion, maybe kind of workaroundish, but may work:

don't disable autentication on the plugin (as the @onny hack, btw: thanks at least for trying something), but rather set a specific user in the onlyoffice plugin options  so that the plugin will hardwire that user on public shared docs by default.
In this way if you share a public link and you've set this "public user" in the onlyoffice plugin options, that user will be used as default to open the document at the plugin level and you (devs) don't have to fiddle with unauthenticated accesses.

Again, I don't know the inner workings of OO plugin, so what I said may be just complete bullshit,  just wanted to spot out a possible path if this can make the feature come to the users.

**Comment by jkaberg** [comment]
Wouldn't it be easier to just mimic what ever Collabora does?

**Comment by Mikescops** [comment]
Thanks @ibnpetr for considering it ! I understand how hard it is to handle such huge projects, thanks for your update 👍

**Comment by dairaine** [comment]
+1 for this feature that is a MUST exigence for many collaboration usecases.

**Comment by dybr** [comment]
+1

**Comment by arnowelzel** [comment]
+1

**Comment by esuslik** [comment]
+1

**Comment by arnowelzel** [comment]
> Sorry for the a slice off-topic but I can't open files when they are shared and readonly on nextcloud , onlyoffice says "format is not supported" , anyone can help me ?
> 
> Thanks

Even though OnlyOffice can read ODT, ODS, DOC or XLS, the files needs to be a format which can be opend in OnlyOffice directly. OpenDocument files (ODT, ODS etc.) or old Microsoft Office files (DOC, XLS etc.) can be opened but they will get converted before you can work with them.

For example, if you have files in ODT format you need convert them first to DOCX before you share them as read only files.
