### ISSUE TITLE
Can't activate the app on OC 9.1.8

### ISSUE THREAD

**Issue by arnaudluti** [ONLYOFFICE/onlyoffice-owncloud#204]
Hi there,

I encounter an issue when trying to activate the app on an oc 9.1.8 freshly updated instance.

I get an error when clicking on activate: "Error: This app cannot be activated because this make the server unstable" (translated from french)

i've tried the two most recent releases of the app, same problem.

Our owncloud is running on centOS 7.2, in the logs i get this

PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/onlyoffice/appinfo/application.php on line 66

Thank you in advance for your return
Arnaud

**Comment by HelenBelova17** [comment]
Hello, **@arnaudluti**, please specify some additional information about the issue:
1. How the app was integrated to owncloud?
2. Is the Document Server installed on the same server where owncloud or on different servers?
3. Did you use the app before upgrade owncloud.
4. Send us a logs you get.
5. Send us a screenshot of an error you describe.

**Comment by romale** [comment]
Hi Helen, i've this issue too (p.s. могу по русски если что).
1. I'm using this how-to:
https://api.onlyoffice.com/editors/owncloud , but a can't enable onlyoffice in step 4, because "Error: this app cannot be enabled because it makes the server unstable"
2. Yes, on the same server
3. No, this is first installation
4. When i try enable onlyoffice plugin from owncloud interface:
`{"reqId":"W5bHwo0tIQHVM7qGs8LBkgAAAAA","remoteAddr":"172.16.0.112","app":"PHP","message":"Can't use method return value in write context at \/var\/www\/owncloud\/apps\/onlyoffice\/appinfo\/application.php#71","level":3,"time":"2018-09-10T19:36:34+00:00","method":"GET","url":"\/index.php\/apps\/files","user":"admin"}`

onlyoffice plugin version 2.0.1, downloaded from https://marketplace.owncloud.com/apps/onlyoffice

**Comment by HelenBelova17** [comment]
Hi, **@romale**, please specify some additional information about the issue:
1. How did you install owncloud? Did you use docker for installing or another way?
2. How did you install Document Server? Are you Running Document Server using HTTPS?

**Comment by romale** [comment]
Hi @HelenBelova17 ,
> Hi, **@romale**, please specify some additional information about the issue:
> 
>     1. How did you install owncloud? Did you use docker for installing or another way?

from tar.gz
 
>     2. How did you install Document Server? Are you Running Document Server using HTTPS?

By this manual:
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs in the latest version of ownCloud and onlyoffice plugin?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
