### ISSUE TITLE
Owncloud and onlyoffice not behaving

### ISSUE THREAD

**Issue by laptopdude90** [ONLYOFFICE/onlyoffice-owncloud#43]
I have onlyoffice running on HTTPS on port 5510, port forwarded. When I go to onlyoffice.mydomain.com:5510, I get the green check mark and "Document server is running". 

If I do wget onlyoffice.mydomain.com:5510 this happens:

ERROR: The certificate of ‘onlyoffice.mydomain.com’ is not trusted.
ERROR: The certificate of ‘onlyoffice.mydomain.com’ is not yet activated.

Attempting to convert a file results in "Failed download converted file" and attempting to open an already converted files results in "The document could not be saved. Please check connection settings or contact your administrator. When you click the 'OK' button, you will be prompted to download the document."

I assume these issues are related, but I'm not sure how to fix them.

**Comment by JohnPerkin** [comment]
Hello @laptopdude90 
On the current moment is released integration app 1.0.4. Please update ownCloud/Nextcloud app and Document Server to the latest versions and tell us if it helped or did not.

**Comment by Mariick** [comment]
Hi @laptopdude90 

These issues are not related to OnlyOffice but only related to the certificate used by your onlyoffice installation nginx server, your *nix server dont recognize it as trusted.

You have two way to resolve this issue : 
1) Trust the self signed certificate by adding it to your *Nix certificate bundle ( eg : update-ca-certificates under Unbuntu/Debian)
2) Get a certificate trusted by public Certificate Authority (free with LetsEncrypt)

**Comment by laptopdude90** [comment]
@Mariick The certificate is already from LetsEncrypt, so I'm not sure why it's throwing that error.

**Comment by Mariick** [comment]
@laptopdude90  i had a similar issue the last week on a compagny server with LetsEncrypt certificate, the reason of this problem, is because the *Nix dont have on his CA Bundle one of the LetsEncrypt certificates authority (there is often issues with Debian Wheezy or [some old Ubuntu distribution](https://github.com/certbot/certbot/issues/2026), and certainly with others old *nix distrib).

So to solve this issue i simply go to [https://letsencrypt.org/certificates/](https://letsencrypt.org/certificates/) and download "**ISRG Root X1 (self-signed)**", "**Let’s Encrypt Authority X3 (IdenTrust cross-signed)**" and "**Let’s Encrypt Authority X3 (Signed by ISRG Root X1)**" and then i import theses root certificate into the *nix CA Bundle (with the update-ca-certificates  in the case of Ubuntu/Debian).

**Comment by MaxOnlyOffice** [comment]
Hello!
I hope you have already solved this issue. If not and it's still actual for you please inform us.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
