### ISSUE TITLE
Feature Request: limit access to certain groups

### ISSUE THREAD

**Issue by wschaft** [ONLYOFFICE/onlyoffice-owncloud#88]
Hi,

We've a rather large ownCloud instance (25K+ users) and it would be a nice feature if we can limit access to the onlyoffice app to certain groups.

See also: http://dev.onlyoffice.org/viewtopic.php?f=53&t=10047

**Comment by alexanderonlyoffice** [comment]
@wschaft, thank you for the suggestion, we will take it into consideration.

**Comment by jbrrrr** [comment]
Hi
For our large Nextcloud instance the limitation to groups is a requirement for the introduction of OnlyOffice. OnlyOffice supporting group limitation would be great news for us.

**Comment by JorgeGNL** [comment]
Waiting for this option...

**Comment by poVoq** [comment]
Any chance that this minor option could be implemented? After all it is a basic core feature of Nextcloud used by many apps. Thanks a lot!

**Comment by VicDeo** [comment]
related to the known  upstream issue https://github.com/owncloud/core/issues/20304

**Comment by MorrisJobke** [comment]
@LinneyS Could you explain the underlying problems with this? Maybe we can help and guide you. In Collabora this was solved with a setting inside the app so that the app is still loaded for all users, but only shown to some of them, while providing all the features: https://github.com/nextcloud/richdocuments/pull/135

Or is this only because a public API is not available when the group limitation is in place - this would then be something like that https://github.com/nextcloud/server/issues/5309

**Comment by LinneyS** [comment]
ownCloud: f5a38c6db3238f39f57cc3e767b640c0f7d733ed
Nextcloud: ONLYOFFICE/onlyoffice-nextcloud@36a2cbd652ba1ac1f7a30ea4cbe0a7f5ad654371
